### ISSUE TITLE
Plugin fails when configured with multiple repositories

### ISSUE THREAD

**Issue by paulieborg** [buildkite-plugins/docker-login-buildkite-plugin#40]
When plugin is configured as follows:
```
    plugins:
    - docker-login#v2.0.1:
        - server: host1.com.au
          username: dockeruser
          password-env: DOCKER_PASSWORD
        - server: host2.com.au
          username: dockeruser
          password-env: DOCKER_PASSWORD
```

The buildkite build fails with:

```
Setting up plugins | 0s
cd /var/lib/buildkite-agent/builds/{agent}/{org}/{repo}
🚨 Error: Failed to parse a plugin definition: Configuration for "github.com/buildkite-plugins/docker-login-buildkite-plugin#v2.0.1" is not a hash
```

**Comment by paulieborg** [comment]
This does however work if I put:
```    
  plugins:
    - docker-login#v2.0.1:
        - server: host1.com.au
          username: dockeruser
          password-env: DOCKER_PASSWORD
    - docker-login#v2.0.1:
        - server: host2.com.au
          username: dockeruser
          password-env: DOCKER_PASSWORD
```
It just runs the login twice ;-)
